### ISSUE TITLE
Sending NFT can permissionlessly extend another NFT's lockup maturity

### ISSUE THREAD

**Issue by ZrowGz** [Byte-Masons/Reliquary#28]
The only check at the start of `shift` is whether the sender is the owner or approved. The sender could send maximum duration assets to a recipient & cause that maturity to increase without their permission. Of course, it could increase it only by the difference in duration & the amount as a percentage of the value that is sent, so it'd be challenging to make this attack cost effective (couldn't be caused by a dust attack). Still, it'd potentially be an unexpected extension of lockup time.

Fixes:
Only allow sending from a shorter duration to a longer duration asset. 
Incorporate an approval the receiving NFT owner sets to say "receiving can allow increases in time by X basis points/percentage."

**Comment by Zokunei** [comment]
Hi, thanks for contributing and taking the time to make a PR. I'm trying to get a better understanding of this issue and make sure we're on the same page about expected behavior. First, you say "The only check at the start of shift is whether the sender is the owner or approved." This is true, but it is true for [both](https://github.com/Byte-Masons/Reliquary/blob/a5e58226329760e16819ed31c7fc40248e6cee00/contracts/Reliquary.sol#LL491C1-L492C1) the `fromId` and the `toId`, so it is unclear that the shift function could be used to impact an NFT the sender is not already the owner of or approved to transfer. Can you show a proof of concept demonstrating this (where owner of `fromId` and `toId` are different and neither has approved the other address)?

Also, there is nothing I would refer to as "lockup time" in the Reliquary contract, as users can withdraw their funds at any time. The only way added maturity could negatively impact a user is if the pool's `levels` contain `multipliers` that decrease at higher `requiredMaturities`, which is something that is yet to be tested.

**Comment by ZrowGz** [comment]
Ah, I was thinking the "maturity" was an enforced duration, not just a boost.
